<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite thread-count="10" parallel="tests" name="Failed suite [Suite]" guice-stage="DEVELOPMENT">
  <test thread-count="10" parallel="tests" name="SubmitOrder(failed)">
    <classes>
      <class name="Udemyacademy.PageObjects.SubmitOrderTest">
        <methods>
          <include name="verifyOrder"/>
          <include name="closeApp"/>
          <include name="submit"/>
          <include name="launchApp"/>
        </methods>
      </class> <!-- Udemyacademy.PageObjects.SubmitOrderTest -->
    </classes>
  </test> <!-- SubmitOrder(failed) -->
  <test thread-count="10" parallel="tests" name="ErrorValidation(failed)">
    <classes>
      <class name="Udemyacademy.PageObjects.ErrorValidations">
        <methods>
          <include name="loginErrorValidation"/>
          <include name="closeApp"/>
          <include name="launchApp"/>
          <include name="productErrorValidation"/>
        </methods>
      </class> <!-- Udemyacademy.PageObjects.ErrorValidations -->
    </classes>
  </test> <!-- ErrorValidation(failed) -->
</suite> <!-- Failed suite [Suite] -->
